title: Торсуков Алексей
description: >-
  QA Automation Engineer, работаю в BIOCAD
lang: ru
timezone: Europe/Moscow
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/atrskv/atrskv.github.io
mode: dark # or light

author:
  name: Торсуков Алексей # author name
  bio: >- 
    <b>QA Automation Engineer</b>, <br>
    работаю в <a href="https://biocad.ru" target="_blank"><b>BIOCAD</b></a>
  username: atrskv
  github: atrskv
  twitter: twitter_username # TODO: ...
  facebook: facebook_username # TODO: ...
  email: atrskv@ya.ru
  avatar: /assets/img/avatar.jpg

url: # ...
baseurl: # ...
permalink: /:title/
google_analytics:
fb_appid:

collections:
  posts:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

number_of_posts: 5

sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
